
TYPE
	ExtendedComms_enum : 
		(
		WORD_MANIPULATION,
		READ_ACTPRESS_W1,
		READ_ACTPRESS_W2,
		READ_ACTPRESS_W3,
		READ_ACTPRESS_W4,
		WRITE_SETPRESS_W1,
		WRITE_SETPRESS_W2,
		WRITE_SETPRESS_W3,
		WRITE_SETPRESS_W4,
		READ_TANKLEVEL_W1,
		MODBUS_ERROR
		);
END_TYPE
