
TYPE
	ServoRamState_enum : 
		(
		SERVORAM_WAIT_FOR_HOME := 0,
		SERVORAM_IDLE := 10,
		SERVORAM_WAITING_ON_BOX := 15,
		SERVORAM_MOVE_TO_END := 20,
		SERVORAM_DWELL_AT_END := 40,
		SERVORAM_MOVE_TO_START := 60,
		SERVORAM_DWELL_AT_START := 80,
		SERVORAM_ERROR := 999
		);
END_TYPE
