
TYPE
	ServoHopperState_enum : 
		(
		SERVOHOPPER_WAIT_FOR_HOME := 0,
		SERVOHOPPER_IDLE := 5,
		SERVOHOPPER_MOVE_VELOCITY := 10,
		SERVOHOPPER_COOLDOWN := 15,
		SERVOHOPPER_ERROR := 999,
		SERVOHOPPER_MOVE_TO_END := 20,
		SERVOHOPPER_DWELL_AT_END := 40,
		SERVOHOPPER_MOVE_TO_START := 60,
		SERVOHOPPER_DWELL_AT_START := 80
		);
END_TYPE
