
TYPE
	BlissSideCheckStates_enum : 
		(
		SIDE_CHECK_IDLE,
		SIDE_CHECK_FIRST_CYCLE,
		SIDE_CHECK_LOOK_FOR_EYE,
		SIDE_CHECK_EYE_FOUND,
		SIDE_CHECK_EYE_MISSED
		);
	BlissBodyCheckStates_enum : 
		(
		BODY_CHECK_IDLE,
		BODY_CHECK_FIRST_CYCLE,
		BODY_CHECK_LOOK_FOR_EYE,
		BODY_CHECK_EYE_FOUND,
		BODY_CHECK_EYE_MISSED
		);
	State_enum : 
		(
		PICKANDPLACE_ERROR := 99,
		PICKANDPLACE_RETURN := 3,
		PICKANDPLACE_DWELL := 2,
		PICKANDPLACE_MOVE_FORWARD := 1,
		PICKANDPLACE_START := 0
		);
END_TYPE
