
TYPE
	DUT_NDSN_ADI : 	STRUCT 
		ui_Size : UINT;
		ui_ADI : UINT;
	END_STRUCT;
	DUT_NDSN_Inventory : 	STRUCT 
		b_r_TempCtrl_Board1 : BOOL;
		b_r_TempCtrl_Board2 : BOOL;
		b_r_TempCtrl_Board3 : BOOL;
		b_r_TempCtrl_Board4 : BOOL;
		b_r_OEM_Unit : BOOL;
		b_r_OLED_Unit : BOOL;
		b_r_WIFI_Board : BOOL;
		b_r_Refill_Board : BOOL;
		b_r_Anybus_Board : BOOL;
		b_r_Press_Sensor : BOOL;
		b_r_Press_CtrlValve : BOOL;
		i_r_NumOfTempZones_Internal : INT;
		i_r_NumOfTempZones_External : INT;
		i_r_NumOfMotors : INT;
		i_r_NumOfPumps : INT;
		i_r_NumOfATS : INT;
		i_r_NumOfWebClients : INT;
	END_STRUCT;
	DUT_NDSN_Flex : 	STRUCT 
		b_r_SystemReady : BOOL;
		b_r_Fault : BOOL;
		b_r_Alert : BOOL;
		b_r_Stop : BOOL;
		b_r_LostCommunication : BOOL;
		b_w_ClearAlertFault : BOOL;
		b_r_TemperatureReady : BOOL;
		b_r_HeatersOn : BOOL;
		b_r_StandbyOn : BOOL;
		b_r_TemperatureAlert : BOOL;
		b_r_TemperatureFault : BOOL;
		b_r_PumpRunning : BOOL;
		b_r_PumpEnabled : BOOL;
		b_r_Purging : BOOL;
		b_r_TankLevelEmpty : BOOL;
		b_r_TankLevelLow : BOOL;
		b_r_FillSysAlert : BOOL;
		b_r_FillSysFault : BOOL;
		b_r_Filling : BOOL;
		b_r_LidOpen : BOOL;
		b_r_EmptyCalibrated : BOOL;
		b_w_HeatersOnOff : BOOL;
		b_w_StandbyOnOff : BOOL;
		b_w_PumpOnOff : BOOL;
		b_w_Purge : BOOL;
		b_w_ManualFill : BOOL;
		b_w_CalibrateEmpty : BOOL;
		b_w_CalibrateFull : BOOL;
		i_rw_Temp_arr_ZoneSP : ARRAY[0..17]OF INT;
		i_rw_Temp_arr_ZoneActivate : ARRAY[0..17]OF INT;
		i_rw_Temp_GlobalStandbyDelta : INT;
		i_rw_Temp_ManualStandyDuration : INT;
		i_rw_Temp_AutoEnterStandbyTm : INT;
		i_rw_Temp_AutoHeaterOffTime : INT;
		i_rw_Temp_AutoStandbySource : INT;
		i_rw_Temp_UnderTempDelta : INT;
		i_rw_Temp_OverTempDelta : INT;
		i_rw_Temp_Unit : INT;
		i_rw_Temp_GlobalSP : INT;
		i_rw_Temp_GlbalHoseSP : INT;
		i_rw_Temp_GlobalGunSP : INT;
		i_rw_Press_Unit : INT;
		r_rw_Press_SP : REAL;
		r_rw_Press_MaxPressLimit : REAL;
		r_rw_Press_MinPressLimit : REAL;
		r_rw_Press_UnderPressDelta : REAL;
		r_rw_Press_OverPressDelta : REAL;
		i_rw_Press_EnableHighLowAlert : INT;
		i_rw_Press_EnableHydrScale : INT;
		i_rw_Fill_EnableFill : INT;
		i_rw_Fill_TargetFillLevel : INT;
		i_rw_Fill_MaxFillTime : INT;
		i_rw_Fill_AlertStopDelayTime : INT;
		i_rw_Fill_LowLevelThreshold : INT;
		i_rw_Fill_LidOpenAlertTime : INT;
		i_rw_Fill_EmptyStopOnOff : INT;
		i_rw_Pump_AutoPump : INT;
		i_rw_Gen_ReadyDelayTime : INT;
		i_rw_Gen_MassUnit : INT;
		i_r_Temp_arr_ZoneActual : ARRAY[0..17]OF INT;
		i_r_Temp_arr_ZoneStatus : ARRAY[0..17]OF INT;
		r_r_Press_ActualPressure : REAL;
		i_r_Press_SensorAlarm : INT;
		i_r_Fill_TankLevel : INT;
		i_r_Gen_CurrentFaultCode : INT;
		i_r_Gen_SoftwareVersion : INT;
		di_r_Gen_OperationHrs : DINT;
		i_r_Gen_arr_SysInventory : ARRAY[0..3]OF INT;
		st_r_Devices : DUT_NDSN_Inventory;
	END_STRUCT;
END_TYPE
